import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren, ReactNode } from "react";
import { AppProps } from "next/app";
import { Flex, MantineProvider } from "@mantine/core";
import { theme } from "./config/theme";
import { Notifications } from "@mantine/notifications";
import { ModalsProvider } from "@mantine/modals";
import AOSProvider from "./provider/AOSProvider";

import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/carousel/styles.css";
import "@mantine/carousel/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayout extends PropsWithChildren, AppProps {}

export default function RootLayout({ children, ...props }: IRootLayout) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <MantineProvider theme={theme}>
          <Notifications />
          <ModalsProvider>
            <AOSProvider />
            <Flex
              style={{
                width: "100%",
                maxWidth: "480px", // mobile max width
                minHeight: "100vh",
              }}
            >
              {children}
            </Flex>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
